fylein/fyle-accounting-mappings

fyle_accounting_mappings/models.py, fyle_accounting_mappings/serializers.py, fyle_accounting_mappings/urls.py, fyle_accounting_mappings/views.py, setup.py
Payload 
```json
{
"source_category": {
"id": 31749
},
"destination_account": {
"id": 4168
},
"destination_expense_head": {
"id": null
},
"workspace": 4
}
```
Response
```json
{
"id": 1,
"source_category": {
"id": 31749,
"attribute_type": "CATEGORY",
"display_name": "Category",
"value": "Accm.Depr. Furniture & Fixtures",
"source_id": "129111",
"auto_mapped": false,
"auto_created": false,
"active": null,
"detail": null,
"created_at": "2021-04-12T14:53:34.575391Z",
"updated_at": "2021-04-12T14:53:34.575418Z",
"workspace": 4
},
"destination_account": {
"id": 4168,
"attribute_type": "ACCOUNT",
"display_name": "Account",
"value": "Job Expenses:Cost of Labor:Installation",
"destination_id": "60",
"auto_created": false,
"active": null,
"detail": {
"fully_qualified_name": "Job Expenses:Cost of …
```
=> Category Mappings Table POST / GET

fyle_accounting_mappings/views.py, setup.py
This helps in showing the walkthrough tooltip in the new design
=> Add order by for Mapping Settings GET

fyle_accounting_mappings/views.py, setup.py
https://app.clickup.com/t/85zrn7z2u
https://fylein.slack.com/archives/C02K2KASQDV/p1676433619579899
https://user-images.githubusercontent.com/37061471/219304683-f216baea-5e5e-4f00-b52b-6c4d38d1771d.mov
=> Fix all filter not returning all values

.github/pull_request_template.md, .github/workflows/pr_size.yml
https://app.clickup.com/t/86cwj8ynw
=> chore: Added Github Action

fyle_accounting_mappings/views.py, setup.py
Mappings View for Activity
[Handle Mappings for Activity Category](https://app.clickup.com/t/86cwkgp4t)
=> fix: Mappings View for Activity

.pylintrc, fyle_accounting_mappings/models.py, fyle_accounting_mappings/urls.py, fyle_accounting_mappings/views.py, setup.py
…dels
Please add link here
https://app.clickup.com/1864988/v/l/6-901605343641-1
=> Feat: Add Mixin to add created_by and updated_by for configuration table

fyle_accounting_mappings/models.py, setup.py
fix: add support for handling duplicate destination_id
=> fix: add support for handling duplicate destination_id

fyle_accounting_library/fyle_platform/apps.py, fyle_accounting_library/fyle_platform/constants.py, fyle_accounting_library/fyle_platform/enums.py, fyle_accounting_library/fyle_platform/helpers.py, fyle_accounting_library/fyle_platform/models.py, fyle_accounting_library/rabbitmq/apps.py, setup.py
https://app.clickup.com/t/86cxx5f62
=> feat: Hello World, fyle_accounting_library!

fyle_accounting_library/rabbitmq/data_class.py, setup.py
=> feat: Add RMQ data class

fyle_accounting_library/rabbitmq/connector.py, fyle_accounting_library/rabbitmq/data_class.py, setup.py
=> fix: RMQ data class

fyle_accounting_library/fyle_platform/models.py, setup.py
=> fix: Xero import state key

fyle_accounting_mappings/helpers.py, fyle_accounting_mappings/views.py, setup.py
https://app.clickup.com/t/86cy3y41e
=> feat: add destination_id__in filter for destination attributes

fyle_accounting_library/common_resources/serializers.py, fyle_accounting_library/common_resources/urls.py, fyle_accounting_library/common_resources/views.py, setup.py
https://app.clickup.com/t/86cy68gtk
=> feat: add dimension detail api

fyle_accounting_library/fyle_platform/models.py, setup.py
=> fix: App specific db cols impl

fyle_accounting_library/common_resources/migrations/0001_initial.py, fyle_accounting_library/rabbitmq/migrations/0001_initial.py, setup.py
=> fix: migration dependencies for new setup

fyle_accounting_library/rabbitmq/models.py, setup.py
=> fix: model deletion due to app label

fyle_accounting_library/rabbitmq/models.py, setup.py
=> fix: add rabbitmq label

fyle_accounting_library/fyle_platform/constants.py, setup.py
=> chore: Add internal state

fyle_accounting_library/fyle_platform/constants.py, setup.py
=> fix: internal

fyle_accounting_library/fyle_platform/constants.py, setup.py
=> feat: Add internal choices

fyle_accounting_library/fyle_platform/enums.py, fyle_accounting_library/fyle_platform/helpers.py, fyle_accounting_library/fyle_platform/models.py, setup.py
=> feat: extend support for sage 300

fyle_accounting_mappings/models.py, fyle_accounting_mappings/views.py, setup.py
Please add link here
https://app.clickup.com/1864988/v/l/li/901605343641
=> Feat: Support for adding mapping for bank account in card mapping

fyle_accounting_library/fyle_platform/models.py, fyle_accounting_mappings/models.py, setup.py
=> feat: extend support for qb connector

fyle_accounting_mappings/models.py, fyle_accounting_mappings/serializers.py, fyle_accounting_mappings/views.py, setup.py
Please add link here
https://app.clickup.com/1864988/v/l/li/901605343641
=> Feat: Added support to corporate card mapping to show bank account ma… 

fyle_accounting_mappings/models.py, fyle_accounting_mappings/views.py, setup.py
=> feat: support for handling deletion and recreation in accounting

fyle_accounting_library/fyle_platform/branding.py, fyle_accounting_library/fyle_platform/enums.py, fyle_accounting_library/fyle_platform/helpers.py, setup.py
=> feat: add fund source retrieval support and feature flags based on brand

fyle_accounting_library/fyle_platform/enums.py, setup.py
=> chore: add utility enum

fyle_accounting_mappings/models.py, setup.py
=> fix: disable custom field on rename

fyle_accounting_library/rabbitmq/enums.py, setup.py
=> chore: add enums for exchange

fyle_accounting_mappings/models.py, fyle_accounting_mappings/views.py, setup.py
=> chore: add qbd standarize change

setup.py
=> fix: qbd name

fyle_accounting_mappings/models.py, fyle_accounting_mappings/views.py, setup.py
=> chore: standard import changes for xero

fyle_accounting_mappings/models.py, fyle_accounting_mappings/views.py, setup.py
=> chore: bump version to 2.2.4 and update app name filters for QuickBooks support

fyle_accounting_mappings/models.py, fyle_accounting_mappings/views.py, setup.py
=> chore: add Intacct standardize import changes

fyle_accounting_mappings/models.py, setup.py
https://app.clickup.com/t/86czbf1p1
=> fix: duplicate account sync

fyle_accounting_library/rabbitmq/data_class.py, fyle_accounting_library/rabbitmq/helpers.py, setup.py
=> chore: add Task chain executor for RabbitMQ processing

fyle_accounting_mappings/models.py, setup.py
https://app.clickup.com/t/86czdywrw
=> fix: multiple cost code sync

setup.py
=> chore: version bump for #183

fyle_accounting_mappings/models.py, setup.py
=> fix: allow duplicate values

fyle_accounting_mappings/e2e_fixtures.py
=> fix: better mocks for expense and destination attributes

fyle_accounting_mappings/models.py, setup.py
=> fix: reset destination_account_id if the expense category <> account changes

fyle_accounting_mappings/e2e_fixtures.py, setup.py
=> fix: deactivate existing expense attributes in e2e org setup

fyle_accounting_mappings/views.py, setup.py
fix: Netsuite app name
https://app.clickup.com/t/86czpr47v
=> fix: Netsuite app name

fyle_accounting_library/common_resources/helpers.py, fyle_accounting_library/common_resources/logging_middleware.py, fyle_accounting_library/common_resources/model_fields.py, setup.py
=> chore: add reusable helpers

fyle_accounting_library/rabbitmq/enums.py, setup.py
=> chore: add enum for rabbitmq exchange sage file export

fyle_accounting_library/fyle_platform/models.py, fyle_accounting_mappings/views.py, setup.py
=> feat: add support for Sage File Export API

fyle_accounting_library/fyle_platform/helpers.py, setup.py
=> fix: enum type
